{% set name = "enfrosp" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/enfrosp-{{ version }}.tar.gz
  sha256: f035df2e34db39a0bb89fa1422963e6204878ecff3abb44b00790335dc2eb50d

build:
  entry_points:
    - enfrosp = enfrosp.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python =3.13  # with python !=3.13, the builds hang for hours
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - gdal
    - geoarray
    - numpy
    - scipy

test:
  imports:
    - enfrosp
  commands:
    - pip check
    - enfrosp --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://git.gfz-potsdam.de/EnMAP/GFZ_Tools_EnMAP_BOX/enfrosp
  summary: EnMAP Fast Retrieval Of Snow Properties
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danschef
