{% set name = "enfrosp" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/enfrosp-{{ version }}.tar.gz
  sha256: 1ead1e0a94ae2e5bd1a8ba42809ad5f735e62d516a6d31186e66b1e773b6238e

build:
  entry_points:
    - enfrosp = enfrosp.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - gdal
    - geoarray
    - numpy
    - scipy

test:
  imports:
    - enfrosp
  commands:
    - pip check
    - enfrosp --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://git.gfz-potsdam.de/EnMAP/GFZ_Tools_EnMAP_BOX/enfrosp
  summary: EnMAP Fast Retrieval Of Snow Properties
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danschef
