{% set name = "enfrosp" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/enfrosp-{{ version }}.tar.gz
  sha256: 23c7509cd60b56c80a16b90435399325ae5d73360be6bc141a8ff86271162884

build:
  entry_points:
    - enfrosp = enfrosp.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - gdal
    - geoarray
    - numpy
    - scipy

test:
  imports:
    - enfrosp
  commands:
    - pip check
    - enfrosp --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://git.gfz-potsdam.de/EnMAP/GFZ_Tools_EnMAP_BOX/enfrosp
  summary: EnMAP Fast Retrieval Of Snow Properties
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danschef
